### ISSUE TITLE
Installing “atom-sassc-live@1.0.6” failed

### ISSUE THREAD

**Issue by norbert-codes** [adekbadek/atom-sassc-live#2]
Just tried to install the plugin with atom `1.12.0-beta4`, and got the following error output:
Any chance you can look into it? Otherwise this plugin would be a huge deal for me, exactly what Im looking for. Thanks!

```
> pty.js@0.3.1 install /private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/apm-install-dir-116927-53629-1hzmv0a/node_modules/atom-sassc-live/node_modules/pty.js
> node-gyp rebuild

/private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/apm-install-dir-116927-53629-1hzmv0a
`-- (empty)


make: *** No rule to make target `../../../../../../../../../../../../opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/apm-install-dir-116927-53629-1hzmv0a/node_modules/atom-sassc-live/node_modules/pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/apm-install-dir-116927-53629-1hzmv0a/package.json'
npm WARN apm-install-dir-116927-53629-1hzmv0a No description
npm WARN apm-install-dir-116927-53629-1hzmv0a No repository field.
npm WARN apm-install-dir-116927-53629-1hzmv0a No README data
npm WARN apm-install-dir-116927-53629-1hzmv0a No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom-beta/1.8.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/norbert/.atom/.apm/.apmrc" "--userconfig" "/Users/norbert/.atom/.apmrc" "install" "/private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/d-116927-53629-1wgqkj2/package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/r9/k_y8wx5s2wd1gh9zlfmhqn5w0000gn/T/apm-install-dir-116927-53629-1hzmv0a/npm-debug.log
npm ERR! code 1
```

**Comment by norbert-codes** [comment]
Just a quick addition: Apparently homebrew did not update the folder name on app updates, so its still `/Caskroom/atom-beta/1.8.0-beta3/` , but app package is updated.

**Comment by adekbadek** [comment]
I'll look into it hopefully next week, it seems to be a problem with pty.js

**Comment by adekbadek** [comment]
Can you check now, @nygdjs?
I've publishsed a patch (not related to `pty.js`), and successfully installed `v.1.0.7` on atom `1.12.2`
Another thing I did is rebuilding packages in atom's Incompatible Packages view

**Comment by norbert-codes** [comment]
Sure! And thanks for the quick help. (Will check it on the weekend most probably...)

**Comment by adekbadek** [comment]
closing due to lack of response
