### ISSUE TITLE
package could not be installed

### ISSUE THREAD

**Issue by weshuiz** [adekbadek/atom-sassc-live#6]
i keep getting n error when trying to install im afraid to give the error output becuse personal information might get out aswell package could not be installed?

**Comment by adekbadek** [comment]
Hi @weshuiz! I just reinstalled it and everything went fine. Without the error information there's not much I can do :(

**Comment by electricarts** [comment]
Atom 1.23.0, Mac OS X 10.12.6

I just tried to install the package. This is the error information. 

`Installing “atom-sassc-live@1.0.10” failed.

> java@0.8.0 install /private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr/node_modules/atom-sassc-live/node_modules/java
> node-gyp rebuild

/private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr
`-- (empty)


[node-java] Error: Command failed: /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.

gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr/node_modules/atom-sassc-live/node_modules/java
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr/package.json'
npm WARN apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr No description
npm WARN apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr No repository field.
npm WARN apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr No README data
npm WARN apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mario/.atom/.apm/.apmrc" "--userconfig" "/Users/mario/.atom/.apmrc" "install" "/private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/d-1171022-34443-17sv4u.zzcy9icnmi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/bn/q4vx6_hd0s15lmz9jnr5skjh0000gn/T/apm-install-dir-1171022-34443-1meo73p.42tx0z4cxr/npm-debug.log
npm ERR! code 1`
